### ISSUE TITLE
Consider what happens if a site is deleted, or otherwise wants to withdraw from commons

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Sites#3]
There's no mechanism currently for handling what happens if a site is deleted from the Commons. This was discovered just because I'd been testing by adding and clobbering sites, but it raises the question that I don't think we've addressed: What's the mechanism and circumstances if a site wants to withdraw from the Commons? Given that EmbedCodes should be in play, would we want to let a site withdraw, and make those embeds break? Should we say that once something is in the Commons, it's there forever? (current code, I think, allows removal of individual items, but has nothing for wholesale site removal).

Probably many questions to nail down, and somehow turn into accepted user stories, I think. 

Convo for @sharonmleon @sheilabrennan @kimisgold ?

**Comment by sheilabrennan** [comment]
I think we do need to give site admins the option to pull items from the Commons. We can make it harder, so that they have to go through and unselect all items or collections that have been added to the Commons. 

Could there be a way to not show a Site in the Commons if the Site has shared no items?

**Comment by patrickmj** [comment]
Site admins can pull individual items from the Commons -- currently, that makes them not public in the Commons, but the item still exists. I think that's necessary for the other purpose of the Commons, providing a quick copy of the item in case of data loss from the site (LOCKSS)

The question was more about an entire site saying it doesn't want to be part of the Commons, basically changing its mind about whether it wants to be part of OC. Should that be the equivalent of making it not public. We could certainly do that, and I guess all its items would be made private. Or, would that become a case where everything should be completely deleted, not just made private?

**Comment by sheilabrennan** [comment]
Trying to think this through. 

Since we are not grabbing content, but are asking Site admins to push to the Commons, I think we need to delete from Commons if a Site requests to no longer be part of the Commons.
